# AUTOGENERATED! DO NOT EDIT! File to edit: nbs\23_rnn_vae.ipynb (unless otherwise specified).

__all__ = ['mod_batch']

# Cell

import torch
from torch import nn, optim
from ..architecture import Encoder, Decoder, DownUpConv
from ..utils import Tracker

# Cell

def mod_batch(batch, key="img"):
    """
    transform the batch to be compatible with the network by permuting
    """
    batch[key] = batch[key][0, :, :, :, :]
    batch[key] = batch[key].permute(1, 0, 2, 3)
    return batch