# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"test": "00_demo.ipynb",
         "test2": "00_demo.ipynb"}

modules = ["demo.py"]

doc_url = "https://NikonPic.github.io/deeptool/"

git_url = "https://github.com/NikonPic/deeptool/tree/master/"

def custom_doc_links(name): return None
