# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"MAX_PIXEL_VAL": "00_dataload.ipynb",
         "MEAN": "00_dataload.ipynb",
         "STDDEV": "00_dataload.ipynb",
         "INPUT_DIM": "00_dataload.ipynb",
         "RandomCrop": "00_dataload.ipynb",
         "TriplePrep": "00_dataload.ipynb",
         "MiddleCrop": "00_dataload.ipynb",
         "Rescale": "00_dataload.ipynb",
         "ToTensor": "00_dataload.ipynb",
         "Normalize": "00_dataload.ipynb",
         "weights_init": "01_arch.ipynb",
         "BlurPool3d": "01_arch.ipynb",
         "Quantize": "01_arch.ipynb",
         "ResNetBlock": "01_arch.ipynb",
         "ConvBn": "01_arch.ipynb",
         "ConvTpBn": "01_arch.ipynb",
         "LinearSigmoid": "01_arch.ipynb",
         "DownUpConv": "01_arch.ipynb",
         "Encoder": "01_arch.ipynb",
         "Decoder": "01_arch.ipynb",
         "Discriminator": "01_arch.ipynb"}

modules = ["dataload.py",
           "arch.py"]

doc_url = "https://NikonPic.github.io/deeptool/"

git_url = "https://github.com/NikonPic/deeptool/tree/master/"

def custom_doc_links(name): return None
