# AUTOGENERATED! DO NOT EDIT! File to edit: 00_demo.ipynb (unless otherwise specified).

__all__ = ['test', 'test2']

# Cell
def test(a, b):
    return a+b

# Cell
def test2(a, b, c):
    return a+b+c